### ISSUE TITLE
Интеграция с Google Forms

### ISSUE THREAD

**Issue by fedor57** [fedor57/alumni-auth#14]
Написать Google Apps скрипт для Google Forms, который принимает "оригинальный" код, дергает API, получает маскированный оригинальный код и временный для приложения, записывает оба кода в поля Google Forms.

* В случае ошибки пишет сообщение и не дает перейти на следующий шаг.

**Comment by alexshpilkin** [comment]
«Не даёт перейти на следующий шаг» не очень приветливо, по-моему, — ты хочешь совсем запретить анонимное участие или ручную проверку? Проблема с более технической стороны: в новых гуглоформах (которые https://forms.google.com/) нету деления на шаги или страницы и нету API для кастомной валидации.

(Про интеграцию с гуглоформами в общем я тем не менее думаю.)

**Comment by fedor57** [comment]
Я настрогал гуглоформу, которая делает все, что нужно, пришлю потом. Там есть шаг с переключающим вопросом "есть работающий код под рукой?. Если да, то берем код, проверяем регуляркой и дальше переходим к голосованию. Если нет, то спрашиваем ФИ, класс, профили, емейл и пр, дальше переходим к голосованию. Форму можно заполнять N раз, каждый вариант заполнения - редактировать. Мне нужно сделать что-то вроде кастомной валидации, которая не пропустит дальше, точно также, как и при запрещенном по формату вводе.

**Comment by fedor57** [comment]
Готово, голосование пошло.
