### ISSUE TITLE
Макетный скрипт для Google Forms

### ISSUE THREAD

**Issue by fedor57** [fedor57/alumni-auth#15]
Нам нужно раскопать тему скриптов для Google Apps в применении к гуглоформам. Сценарий примерно такой:

- есть гуглоформа с голосованием, там есть поле для кода
- по событию "поле заполнено" или "завершен шаг с этим полем" нужно выполнить некоторый скрипт для Google Apps
- сформировать http post запрос с кодом в параметрах (ajax или в теле)
- получить ответ на json, отпарсить его
- проверить код ошибки, если 0, то достать поле с "новым кодом" из ответа
- вычистить из формы или таблицы, куда пишется исходный код, этот код. А, возможно, его заэкранировать, заменив часть цифр буквами xxxxxxxxx
- записать новый полученный код еще в одно дополнительное поле выходной таблицы

На этапе разработки макета лучше не требовать реального API и реальной формы для голосования, а тренироваться на кошках. Исправить формирование запроса, парсинг ответа и выбор поля для заполнения мы потом быстро сможем на этапе интеграции.

Можно сделать самостоятельно гуглоформу из одного шага и одного поля для кода. Можно отсылать запросы на какой-нибудь ajax-сервер через POST, например, вот этот

https://resttesttest.com

Не важно, что это левое API и там нет нужных данных, главное, будет референсный код.

**Comment by fedor57** [comment]
Несколько ссылок по теме
- https://developers.google.com/apps-script/guides/services/external - JSON GET и парсинг ответа
- http://stackoverflow.com/questions/14742350/google-apps-script-make-http-post - пример отсылки HTTP POST
- https://ctrlq.org/code/19871-get-post-requests-google-script - пример и того, другого

**Comment by fedor57** [comment]
Вот reference документации по формам
https://developers.google.com/apps-script/reference/forms/

**Comment by vadz** [comment]
Я начал смотреть, но тут же столкнулся с проблемой: нет события "поле заполнено" или какого-то похожего, есть только `onSubmit()`, который вызывается только после нажатия "Submit" в самом конце, как это ни странно. Можем ли мы с этим жить или никак? Что нам реально надо, может ли быть достаточно просто взять этот код из формы и куда-то отправить, даже если другие шаги из https://github.com/fedor57/alumni-auth/issues/15#issue-221305275 выполнить не удастся?

На всякий случай, вот моя [тестовая форма](https://goo.gl/forms/7t0MsJ6jKSk9tkVE2), могу ею поделиться если кому-то хочется попробовать самому.

**Comment by fedor57** [comment]
Можем с этим жить. Код можно заменять в самый последний момент. Есть ли событие "отправлен шаг", нет ли флажка у формы "сохранять по частям"?

-- 
С приветом, Федор

**Comment by vadz** [comment]
К сожалению, я не нашёл никаких других событий.

Хуже то, что пока что я не могу понять как добраться до значений полей формы, согласно [документации](https://developers.google.com/apps-script/guides/triggers/events#form-submit_3) они должны быть в `е.response`, но только их там нет: у меня код просто
```js
function onSubmit(e) {
  Logger.log("onSubmit(%s)", JSON.stringify(e));
  ...
}
```
и в логах видно только:
```
[17-04-15 18:56:23:584 CEST] onSubmit({"response":{},"source":{},"authMode":{},"triggerUid":1870249629})
```
Я подозреваю, что это какая-то лажа с permissions (`authMode` точно не должна бы была быть пустой), но пока не знаю как с этим бороться.

**Comment by vadz** [comment]
Я как минимум временно сдаюсь, не могу понять почему у меня нет значений. Написал про это [вопрос](http://stackoverflow.com/questions/43429161/how-to-get-form-values-in-the-submit-event-handler), м.б. кто-нибудь поможет, хотя, судя по стастистике ответов на вопросы с этими тегами, это маловероятно...

**Comment by vadz** [comment]
ОК, этот вопрос снялся, оказывается `JSON.stringify()` просто не работает с объектами GS, т.е. несмотря на `{}`, данные там на самом деле есть. Т.е. я могу взять код из формы, куда-то его послать и что-то получить. Вопрос в том, что теперь дальше с этим делать?

**Comment by fedor57** [comment]
Отлично! Там Коля накоммитил что-то про API. Т.е. если все срастется, в принципе, можно было бы попробовать собрать.

**Comment by fedor57** [comment]
Не, судя по коммиту, еще не готово:
https://github.com/fedor57/alumni-auth/commit/79547c3a6726d8af48102c0b047d055058d624e1

**Comment by fedor57** [comment]
А что-то полученное в json ты умеешь разбирать? А писать в колонки по результату заполнения формы? А не писать исходный код в базу?

**Comment by vadz** [comment]
`JSON.parse()`, вроде, работает:

```js
  var res = UrlFetchApp.fetch("https://jsonplaceholder.typicode.com/todos/17");
  if (res.getResponseCode() == 200) {
    var data = JSON.parse(res.getContentText());
    Logger.log("got title=%s", data.title);
  }
```

Про писать в колонку не понял: в колонку чего? Google Spreadsheet какого-то? Наверное могу, но пока не пробовал.

А вот не писать в базу похоже не могу, т.е. результаты сохраняются независимо от того, что я делай в "form submit". Я где-то видел, что вроде можно что-то как-то с сырым JS делать, чтобы это обойти, но я не уверен, что меня на это хватит.

**Comment by fedor57** [comment]
Нам нужно не сохранять исходный код из поля формы, но сохранять, полученный через api.

-- 
С приветом, Федор

**Comment by vadz** [comment]
Я могу сохранять в Google Sheet, могу посылать какому-то другому серверу. Прямо так сохранять в форме не получается, но может быть тоже можно.

Мне трудно понять, что лучше, потому что я до сих пор не понимаю что мы конкретно делаем, так что было бы хорошо чтобы ты либо мне это объяснил (в слаке?), либо решил что-то сам и просто сказал мне, что надо сделать. Спасибо!

**Comment by fedor57** [comment]
Вот тут есть детальная информация, ссылка на вики и обсуждение

https://github.com/fedor57/alumni-auth/issues/9

**Comment by mxposed** [comment]
Я готовлю ручку по адресу `auth.alumni57.ru/api/v1/exchange_code`
Она принимает 3 POST параметра
1. `code` — то, что ввёл пользователь
2. `app` — идентификатор приложения, которое запрашивает код (тут, видимо, election2017 или что-то такое)
3. `valid_for` — опциональный, количество секунд, в течение которых временный код будет действовать. По дефолту, думаю, будем выставлять 10 минут.

Если всё хорошо, то в ответ будет json вида:
```
{
  "code": "<temporary code>",
  "original_code": "<masked original code>",
  "valid_for": "<number of seconds the code will be valid for>"
}
```

Если плохо, то json вида (и статус ≠ 200)
```
{
  "status": "<technical status, i.e. bad_request>",
  "error": "<human readable error>"
}
```

Формат и прочее обсуждаемы) Надеюсь это выкатить сегодня

**Comment by fedor57** [comment]
Отлично! Предлагаю коррекции по названиям:
В запросе:
- get_app_code
- valid_for - по умолчанию 1 месяц ;)
В ответе:
- expires - unix GMT таймстемп экспирации
- expires_date - human readable дата-время экспирации 

Почему в ответе нельзя valid_for, потому, что мы не знаем, когда получили ответ, и его смысл теряется со временем.

**Comment by fedor57** [comment]
Сохранять в форме - не обязательно, главное, чтобы в таблице, куда пишутся результаты, оказывался маскированный оригинальный код, НЕ оставался оригинальный, попадал возвращенный код приложения и время обращения.

**Comment by vadz** [comment]
Где мы сейчас эти результаты сохраняем? Как я уже писал, я вижу 2 варианта:

1. Добавлять строку в какой-то Google Sheet (как его обезопасить от несанкционированного изменения, это отдельный вопрос...).
2. Посылать введённые значения куда-то ещё.

Мы что делаем, (1) или (2) или что-то совсем другое?

Ещё одна проблема заключается в том, что я пока не знаю как показать пользователю ошибку если она произошла в `onSubmit()`.

**Comment by fedor57** [comment]
Да, я бы добавил в ответ API - response_time, чтобы поле status имело больше смысла. В каком формате - timestamp или human readable, нужно подумать, может быть, два поля, чтобы было в обоих.

Например,
expires_at
expires_date
response_at
response_date

_at - это таймстепмы
_date - это 17.04.2017 14:59:01

Нужно будет установить для spreadsheet российскую локаль только

**Comment by fedor57** [comment]
Гуглоформа настраивается так, что она сохраняет результаты ввода в Google Spreadsheet, которая сама создается и прицепляется к гуглоформе. Каждое поле формы попадает в отдельную колонку. 

Если позволяют настройки, пользователь может а) корректировать поля, которые только что ввел (кнопка Back в браузере) б) Запускать заполнение формы заново, тогда создается новая строка. Нам нужны оба этих режима.

Соответственно, что мы делаем с помочью скрипта, это вмешиваемся в этот механизм: а) пишем в одну из колонок не совсем то, что пользователь туда ввел (маскированный код вместо оригинального) б) заполняем дополнительную колонку (временный код), а также, возможно, дату получения временного кода.

**Comment by mxposed** [comment]
Федя, а зачем месяц? Если таймстемп действия будет таким же, как время выписки кода, то можно хоть 5 секунд туда писать.

**Comment by vadz** [comment]
Скелет скрипта сделан, т.е. он берёт код из формы и заменяет код из шита на результат возвращённый какой-то функцией. Теперь осталось только засунуть в эту функцию вызов [UrlFetchApp.fetch()](https://developers.google.com/apps-script/reference/url-fetch/) и всё должно быть хорошо.

**Comment by fedor57** [comment]
Про месяц: я рассчитывал на "бинарный" способ использования временных кодов. Они сами выписываются, если вводить оригинальный. А также они показываются в интерфейсе типа auth.alumni57.ru, оттуда их можно копипейстить и вводить в директорию-голосовалку. Чтобы это работало, нужно, чтобы он был не протухший.

Если в API вводим временный и он действует, то API возвращает тот же код. Если уже не действует, то нужно либо ввести оригинальный, либо сходить с оригинальным в auth.alumni57.ru.

**Comment by mxposed** [comment]
А, понял. Хорошо. Но я не факт, что успею интерфейс для выписывания временных в auth

**Comment by vadz** [comment]
На всякий случай, вот скрипт:

```js
// The ID of the associated sheet: it might be surmised that using
// getActiveSheet() would work, but it doesn't, so do it like this
// with openById().
//
// Weirdly enough, using "const" here results in an error, go figure.
var sheet_id = "********";

function mangle_code(code) {
  return "*** mangled " + code + " ***";
}

function onSubmitForm(e) {
  Logger.log("onSubmitForm(%s)", e);
  if (e.response === undefined) {
    Logger.log("*** ERROR: missing response, review permissions");
    return;
  }

  // The hardcoded title of the code question, this will need to be
  // updated if it changes in the form.
  const code_title = "Введите свой код выпускника";
  
  // Find the code among the responses, knowing that it might not be
  // there at all.
  var code;
  var items = e.response.getItemResponses();
  for (i in items) {
    if (items[i].getItem().getTitle() == code_title) {
      code = items[i].getResponse();
      break;
    }
  }
  
  var ss = SpreadsheetApp.openById(sheet_id);
  var data = ss.getDataRange();
  
  // Now find the column containing it in the sheet. Just hardcoding it
  // would have been simpler, but this is more flexible:
  var code_col;
  for (var i = 1; i <= ss.getLastColumn(); i++) {
    if (data.getCell(1, i).getValue() == code_title) {
      code_col = i;
      break;
    }
  }
  
  if (code_col === undefined) {
    Logger.log("*** ERROR: column \"%s\" not found in the sheet", code_title);
    return;
  }
 
  // We assume that our row is always the last one added. No idea if this
  // is really correct for concurrent form submissions, but let's hope it is...
  var row = ss.getLastRow();

  var mangled_code;
  if (code === undefined) {
    Logger.log("Code not used");
    
    // We may still need to clear it if the user is editing a previous answer
    // which did use the code.
    mangled_code = "";
  } else {
    Logger.log("Code from form: %s", code);
  
    var sheet_code = ss.getSheetValues(row, code_col, 1, 1)[0][0];
    Logger.log("Code from sheet: %s", sheet_code);

    if (sheet_code != code) {
      Logger.log("*** ERROR: codes differ, not updating");
      return;
    }
    
    mangled_code = mangle_code(code);
    
    Logger.log("Code used, replacing it with \"%s\"", mangled_code);
  }
  
  data.getCell(row, code_col).setValue(mangled_code);
}

// This is a useful function to have to execute it manually from the script editor
// to force the prompt about missing permissions when/if necessary.
function dummy() {
  var ss = SpreadsheetApp.openById(sheet_id);
  Logger.log("There are %s responses currently", ss.getLastRow() - 1);
}
```

**Comment by fedor57** [comment]
Супер, а логгер пишет в почту?

**Comment by vadz** [comment]
Нет, логгер пишет в лог на сервера, доступ к которому (насколько мне известно) есть только из меню "View|Logs" (и только к одному последнему запуску!!).

Но уведомления об ошибках приходят мне в почту (см "Edit|Current project's triggers").

**Comment by mxposed** [comment]
Ручка готова, только адрес поменялся на `auth.alumni57.ru/api/v1/get_app_code`
Код приложения для тестирования: test

**Comment by mxposed** [comment]
Я доделал скрипт для формы, чтобы он делал запрос, и протестил на простом случае. Давайте вставим его в грядущую форму?

**Comment by fedor57** [comment]
Поработали великолепно, всем спасибо!
