### ISSUE TITLE
Разделить имя и фамилию в базе

### ISSUE THREAD

**Issue by alexshpilkin** [fedor57/alumni-auth#4]
Сабж. Это нетрудно сделать простым миграционным скриптом — не из двух слов состоит всего несколько имён. Одновременно это надо сделать на `sch57.ru` (мне).

**Comment by fedor57** [comment]
Предлагаю пока не делать, это не очень нужно. В проектах типа директории тоже заложились на то, что это одно поле.

**Comment by alexshpilkin** [comment]
> В проектах типа директории тоже заложились на то, что это одно поле.

Ай-ай-ай. Примерно потому я и предлагаю это переправить сейчас, чтобы нас не определяло моё решение их не разделять, принятое в 2010-м году. Я понимаю, что это не приоритет технически (и потому не пытаюсь сделать вотпрямщас), но не хотелось бы, чтобы это распространилось неограниченно.

Уже сейчас подпись в формате «Фамилия Имя» в пригласительном письме выглядит неестественно; я ожидаю, что в директории таких случаев будет больше. Собственно, даже в списке выпускников я собирался эти поля разделить, пока не понял, что формат «Имя Фамилия» нигде не требуется.

**Comment by fedor57** [comment]
Я предлагаю сейчас не трогать, но ничего нам не мешает дополнительно потом накопить более детальную информацию о различных представлениях имени. В целом, у нас относительно статичный набор людей, а исходное ФИО не меняется, может только добавиться дополнительное новое.

Простота - это неплохо, если решает задачу. Я старался везде облегчать код и модель данных. Все-таки, у нас внутренний инструмент для нескольких тыс. человек, это не мегасервис, где стоит шлифовать мелочи.
