### ISSUE TITLE
Ссылки с кодом не работают

### ISSUE THREAD

**Issue by alexshpilkin** [fedor57/alumni-auth#5]
1. UX ссылок со встроенным кодом сейчас странный, т. е. нигде не объяснено, что есть код, а есть ссылка, и они отличаются. Пользователи нас не полюбят.
2. Ссылка с кодом не работает, потому что соответствующий `route` направляется на `views.index`, который его не обрабатывает.
3. Нужно помнить, что акт влогина —  активный, и по GET-запросу его делать некошерно (для GETов даже префетчинг разрешён). Нужна отдельная(!) от `views.index` страница, спрашивающая «Хотите войти как такой-то?». У гугла похожая страничка есть, например.
4. После влогина нужно перенаправлять на корень, потому что иначе код сливается в `Referer`.
5. Оффтопик: Неизвестно, что делает во `views.index` обработка POSTа логина. (Надо внимательно прочитать, не сливает ли этот код какую-нибудь инфу timing-атакам.)

**Comment by fedor57** [comment]
В старой версии у нас на странице, авторизованной кодом, этот код показывался в открытом виде. Поэтому после клика на ссылку можно было код увидеть и скопировать. Сейчас это не так, поэтому код в чистом виде в приглашении обязателен. Если передавать код с # и не автологиниться, то, кажется, проблем не должно быть.

Если есть ссылки наружу, а они могут быть, то редирект после логина стоит делать. Вообще, лучше после любого поста по форме делать редирект.

**Comment by alexshpilkin** [comment]
Прости, я наконец просёк идею с кодом во фрагменте. C «не автологиниться» это действительно возможный вариант, нужно только не забыть, что человек может быть как уже залогинен, так и нет (отмотать страницу до поля ввода?). А то по GET-у входить (а также отключать коды, ...) как-то совсем плохо, ведь даже CSRF-защита джанговская GET-ы не проверяет.

**Comment by mxposed** [comment]
Кажется, это больше не актуально, мы убрали ссылки с кодом вообще
