### ISSUE TITLE
Читабельные коды

### ISSUE THREAD

**Issue by alexshpilkin** [fedor57/alumni-auth#6]
«Продиктовать по телефону», написать на бумажке и другие low-tech варианты передачи кода мне очень хотелось бы поддерживать, но для этого цифры надо погруппировать.

@fedor57 говорит, что коды и так слишком длинные. Хорошо, не спорю, давайте искать, как укоротить.
*   Нужен ли префикс `57-` хоть для чего-нибудь, кроме примера с `lyc-` на главной?
*   Обязательно ли коды должны быть числовыми, или можно и буквенные? (Не обязательно весь алфавит, можно без неудобных пар вроде I/1, O/0).

    Отвечаю сам себе: числовые как раз диктовать сильно удобнее, хотя вводить — пофиг. Но буквенные могут быть короче (10^16 < 32^11 для алфавита в 8 цифр и 24 буквы). Пример популярного буквенного кода — SWIFT/BIC.

*    Зачем ещё может быть интересно укоротить код: добавить контрольные цифры, чтобы можно было с уверенностью говорить юзеру, когда он просто опечатался (полезно ли это? в ISBN, IBAN, кредитках, &c. такое есть).

**Comment by fedor57** [comment]
Сейчас код 16 цифр - похож на номер кредитки. Из него мы последние 4 показываем, 12 - секретных.  57- часть некой сигнатуры для лишней проверки. 1990v может уйти, когда будем, например, раздавать учителям. 

Я думаю, что текущий вариант не очень плохой, нет особых причин, чтобы его еще улучшать.
